FROM python:3.11-slim-bullseye

WORKDIR /app

COPY requirements-ARMv7.txt .

ENV CRYPTOGRAPHY_DONT_BUILD_RUST=1

RUN apt-get update && apt-get install -y gcc libffi-dev libssl-dev && \
    python3 -m pip install --upgrade pip && \
    python3 -m pip install --no-cache-dir -r requirements-ARMv7.txt && \
    apt-get clean && rm -rf /var/cache/apt/archives && rm -rf /var/cache/apt/lists && \
    python3 -m pip cache purge

COPY . .

CMD ["python", "pull_http_file_put_blob.py"]
